### ISSUE TITLE
Port script to Linux/macOS

### ISSUE THREAD

**Issue by rohitjha** [Eltion/Kissanime-Downloader#1]
I was thinking of porting Downloader.bat to Linux/macOS/*nix operating systems (as a shell script). If it's alright with you, I'd be happy to submit a PR once I've done so.

**Comment by Eltion** [comment]
I have a script that works for linux since most of the time I use kali linux, I think I should post it for the few people that may use linux, about macOS I think that the syntax should be the same(shell script) but I never used macOS before so I think that it would really help the macOS user if you would do that. THANKS.

**Comment by Eltion** [comment]
I think someone already done it https://github.com/ceesvanegmond/Kissanime-Downloader/tree/ceesvanegmond-patch-1
